# Generated by Django 5.2.17 on 2026-08-16 10:55

import apps.core.utils.id_generator
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_enforce_unique_active_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('direct', 'Direct')], default='direct', max_length=16)),
                ('context_type', models.CharField(choices=[('none', 'None'), ('workout_session', 'Workout Session')], default='none', max_length=32)),
                ('context_id', models.CharField(blank=True, max_length=36, null=True)),
                ('participant_key', models.CharField(db_index=True, max_length=160)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, max_length=140)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_conversations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('role_at_join', models.CharField(choices=[('coach', 'Coach'), ('athlete', 'Athlete'), ('owner', 'Owner')], max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='communication.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversation participant',
                'verbose_name_plural': 'conversation participants',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=2000)),
                ('client_message_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.conversation')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('message.sent', 'message.sent'), ('workout.completed', 'workout.completed'), ('feedback_flag.created', 'feedback_flag.created')], db_index=True, max_length=48)),
                ('category', models.CharField(choices=[('messaging', 'Messaging'), ('training', 'Training'), ('safety', 'Safety'), ('account', 'Account')], db_index=True, max_length=24)),
                ('title_key', models.CharField(max_length=64)),
                ('body_key', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(max_length=128)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organizations.organization')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', 'in_app'), ('email', 'email'), ('web_push', 'web_push')], max_length=16)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('suppressed', 'Suppressed'), ('dead_letter', 'Dead Letter')], default='pending', max_length=16)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('provider_ref_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='communication.notification')),
            ],
            options={
                'verbose_name': 'delivery attempt',
                'verbose_name_plural': 'delivery attempts',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('message.sent', 'message.sent'), ('workout.completed', 'workout.completed'), ('feedback_flag.created', 'feedback_flag.created')], max_length=48)),
                ('channel', models.CharField(choices=[('in_app', 'in_app'), ('email', 'email'), ('web_push', 'web_push')], max_length=16)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferenceProfile',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.CharField(default='22:00', max_length=5)),
                ('quiet_hours_end', models.CharField(default='07:00', max_length=5)),
                ('web_push_permission_state', models.CharField(choices=[('unknown', 'Unknown'), ('granted', 'Granted'), ('denied', 'Denied')], default='unknown', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference profile',
                'verbose_name_plural': 'notification preference profiles',
            },
        ),
        migrations.CreateModel(
            name='OutboxRecord',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('event_id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, max_length=36, unique=True)),
                ('event_type', models.CharField(choices=[('message.sent', 'message.sent'), ('workout.completed', 'workout.completed'), ('feedback_flag.created', 'feedback_flag.created')], db_index=True, max_length=48)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('subject_type', models.CharField(max_length=64)),
                ('subject_id', models.CharField(max_length=36)),
                ('correlation_id', models.CharField(blank=True, max_length=36)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('processed', 'Processed'), ('failed', 'Failed'), ('dead_letter', 'Dead Letter')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_token', models.CharField(blank=True, max_length=36)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emitted_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_records', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'outbox record',
                'verbose_name_plural': 'outbox records',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization', '-last_message_at'], name='communicati_organiz_246991_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization', 'context_type', 'context_id'], name='communicati_organiz_2a5cb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('organization', 'kind', 'participant_key'), name='unique_direct_conversation_per_pair'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user', 'left_at'], name='communicati_user_id_7f0c10_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['conversation', 'left_at'], name='communicati_convers_a4129d_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_participant_per_conversation'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at', '-id'], name='communicati_convers_8f6bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_user', '-created_at'], name='communicati_sender__a9e8e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('conversation', 'sender_user', 'client_message_id'), name='unique_client_message_id_per_sender'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_user', 'read_at', '-created_at'], name='communicati_recipie_469814_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_user', '-created_at', '-id'], name='communicati_recipie_c295ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('recipient_user', 'dedupe_key'), name='unique_notification_per_recipient_event'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['notification', 'channel'], name='communicati_notific_e35736_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.UniqueConstraint(fields=('notification', 'channel', 'attempt_number'), name='unique_delivery_attempt_per_channel'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'event_type'], name='communicati_user_id_a573fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'event_type', 'channel'), name='unique_preference_per_user_event_channel'),
        ),
        migrations.AddIndex(
            model_name='outboxrecord',
            index=models.Index(fields=['status', 'next_attempt_at'], name='communicati_status_c4ff25_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxrecord',
            index=models.Index(fields=['event_type', '-created_at'], name='communicati_event_t_5db284_idx'),
        ),
    ]
