# Generated by Django 5.2.17 on 2026-08-14 09:44

import apps.core.utils.id_generator
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_enforce_unique_active_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('movement_pattern', models.CharField(choices=[('squat', 'Squat'), ('hinge', 'Hinge'), ('horizontal_push', 'Horizontal Push'), ('horizontal_pull', 'Horizontal Pull'), ('vertical_push', 'Vertical Push'), ('vertical_pull', 'Vertical Pull'), ('lunge', 'Lunge'), ('carry', 'Carry'), ('isolation', 'Isolation'), ('cardio', 'Cardio'), ('other', 'Other')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('primary_muscles', models.JSONField(default=list)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('equipment_required', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('archived', 'Archived'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_exercises', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseAlias',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('locale', models.CharField(choices=[('fa-IR', 'Persian'), ('en-US', 'English')], max_length=10)),
                ('alias', models.CharField(max_length=200)),
                ('normalized_alias', models.CharField(db_index=True, editable=False, max_length=200)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='exercises.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseTranslation',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('locale', models.CharField(choices=[('fa-IR', 'Persian'), ('en-US', 'English')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=200)),
                ('instructions', models.TextField()),
                ('coaching_cues', models.JSONField(blank=True, default=list)),
                ('common_mistakes', models.JSONField(blank=True, default=list)),
                ('safety_notes', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='exercises.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('video_mp4', 'MP4 video'), ('image_webp', 'WebP image'), ('animation_gif', 'GIF animation')], max_length=20)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('thumbnail_storage_key', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes_size', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='exercises.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='MediaRights',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('license_type', models.CharField(choices=[('original_production', 'Original production'), ('licensed_cc_by', 'CC BY licensed'), ('commercial_license', 'Commercial license'), ('coach_upload', 'Coach upload')], max_length=50)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('creator_attribution', models.CharField(max_length=255)),
                ('permitted_commercial_use', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('media_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='exercises.mediaasset')),
                ('reviewed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_media_rights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['organization', 'status'], name='exercises_e_organiz_0ea3e5_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['movement_pattern', 'difficulty'], name='exercises_e_movemen_1b7e72_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisealias',
            index=models.Index(fields=['locale', 'normalized_alias'], name='exercises_e_locale_020600_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercisealias',
            constraint=models.UniqueConstraint(fields=('exercise', 'locale', 'normalized_alias'), name='unique_normalized_alias'),
        ),
        migrations.AddIndex(
            model_name='exercisetranslation',
            index=models.Index(fields=['locale', 'normalized_name'], name='exercises_e_locale_b13263_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercisetranslation',
            constraint=models.UniqueConstraint(fields=('exercise', 'locale'), name='unique_exercise_locale'),
        ),
    ]
