# Generated by Django 5.2.17 on 2026-08-15 14:30

import apps.core.utils.id_generator
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('organizations', '0002_enforce_unique_active_owner'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('modified', 'Modified')], default='scheduled', max_length=20)),
                ('skip_or_modify_reason', models.TextField(blank=True, null=True)),
                ('session_rpe', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('fatigue_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('athlete_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_sessions', to='organizations.organization')),
                ('program_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_sessions', to='programs.programassignment')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('equipment_unavailable', 'Equipment unavailable'), ('discomfort', 'Discomfort'), ('preference', 'Preference'), ('other', 'Other')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substituted_from', to='exercises.exercise')),
                ('substituted_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substituted_to', to='exercises.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='execution.workoutsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('set_index', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('actual_reps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_load_kg', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actual_rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('is_completed', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set_logs', to='exercises.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='execution.workoutsession')),
            ],
            options={
                'ordering': ['set_index'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackFlag',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(choices=[('joint_pain', 'Joint pain'), ('muscle_strain', 'Muscle strain'), ('dizziness', 'Dizziness'), ('severe_fatigue', 'Severe fatigue')], max_length=30)),
                ('anatomical_location', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('details', models.TextField(help_text='Subjective athlete feedback, not a clinical diagnosis.')),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved')], default='unresolved', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_flags', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_flags', to='execution.workoutsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BodyMetric',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('body_weight', 'Body weight'), ('body_fat_percentage', 'Body fat percentage'), ('waist_circumference', 'Waist circumference'), ('other', 'Other')], max_length=40)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='kg', max_length=5)),
                ('recorded_at', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('athlete_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['athlete_user', 'recorded_at'], name='execution_b_athlete_4887c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('progress_photo', 'Progress photo'), ('nutrition_sharing', 'Nutrition sharing'), ('body_metrics', 'Body metrics')], max_length=30)),
                ('is_granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents_given', to=settings.AUTH_USER_MODEL)),
                ('grantee_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('athlete_user', 'grantee_user', 'consent_type'), name='unique_consent_athlete_grantee_type')],
            },
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('photo_type', models.CharField(choices=[('front', 'Front'), ('side', 'Side'), ('back', 'Back')], max_length=20)),
                ('consent_status', models.BooleanField(default=False, help_text='Snapshot of whether athlete has granted sharing consent for this photo.')),
                ('captured_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('athlete_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_photos', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['athlete_user', 'created_at'], name='execution_p_athlete_c1d76a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['athlete_user', 'scheduled_date', 'status'], name='execution_w_athlete_3cc818_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['organization', 'athlete_user', 'status'], name='execution_w_organiz_8f96a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.UniqueConstraint(fields=('program_assignment', 'scheduled_date'), name='unique_assignment_scheduled_date'),
        ),
        migrations.AddIndex(
            model_name='setlog',
            index=models.Index(fields=['session', 'exercise', 'set_index'], name='execution_s_session_65d5ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='setlog',
            constraint=models.UniqueConstraint(fields=('session', 'exercise', 'set_index'), name='unique_session_exercise_set'),
        ),
        migrations.AddIndex(
            model_name='feedbackflag',
            index=models.Index(fields=['session', 'status'], name='execution_f_session_93597f_idx'),
        ),
    ]
