# Generated by Django 5.2.17 on 2026-08-16 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
        ('organizations', '0002_enforce_unique_active_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymetric',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='body_metrics', to='organizations.organization'),
        ),
    ]
