# Generated by Django 5.2.17 on 2026-08-14 07:18

import apps.core.utils.id_generator
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('auth.registered', 'auth.registered'), ('auth.login', 'auth.login'), ('auth.login_failed', 'auth.login_failed'), ('auth.logout', 'auth.logout'), ('auth.password_reset_requested', 'auth.password_reset_requested'), ('auth.password_reset_completed', 'auth.password_reset_completed'), ('org.created', 'org.created'), ('org.settings_updated', 'org.settings_updated'), ('org.owner_transferred', 'org.owner_transferred'), ('membership.created', 'membership.created'), ('membership.status_changed', 'membership.status_changed'), ('membership.role_changed', 'membership.role_changed'), ('invitation.created', 'invitation.created'), ('invitation.sent', 'invitation.sent'), ('invitation.accepted', 'invitation.accepted'), ('invitation.revoked', 'invitation.revoked')], db_index=True, max_length=100)),
                ('target_entity_type', models.CharField(blank=True, max_length=64)),
                ('target_entity_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'permissions': [('can_view_audit', 'Can view audit events')],
            },
        ),
    ]
