# Generated by Django 5.2.17 on 2026-08-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('auth.registered', 'auth.registered'), ('auth.login', 'auth.login'), ('auth.login_failed', 'auth.login_failed'), ('auth.logout', 'auth.logout'), ('auth.password_reset_requested', 'auth.password_reset_requested'), ('auth.password_reset_completed', 'auth.password_reset_completed'), ('org.created', 'org.created'), ('org.settings_updated', 'org.settings_updated'), ('org.owner_transferred', 'org.owner_transferred'), ('membership.created', 'membership.created'), ('membership.status_changed', 'membership.status_changed'), ('membership.role_changed', 'membership.role_changed'), ('invitation.created', 'invitation.created'), ('invitation.sent', 'invitation.sent'), ('invitation.accepted', 'invitation.accepted'), ('invitation.revoked', 'invitation.revoked'), ('session.started', 'session.started'), ('session.completed', 'session.completed'), ('session.skipped', 'session.skipped'), ('exercise.substituted', 'exercise.substituted'), ('pain.flagged', 'pain.flagged'), ('photo.uploaded', 'photo.uploaded'), ('photo.viewed', 'photo.viewed'), ('metric.recorded', 'metric.recorded'), ('metric.viewed', 'metric.viewed'), ('consent.granted', 'consent.granted'), ('consent.revoked', 'consent.revoked'), ('conversation.created', 'conversation.created'), ('message.sent', 'message.sent'), ('conversation.read', 'conversation.read'), ('notification.preferences_updated', 'notification.preferences_updated'), ('notification.read_all', 'notification.read_all')], db_index=True, max_length=100),
        ),
    ]
