# Generated by Django 5.2.17 on 2026-08-14 09:44

import apps.core.utils.id_generator
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('organizations', '0002_enforce_unique_active_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_goal', models.CharField(choices=[('hypertrophy', 'Hypertrophy'), ('strength', 'Strength'), ('fat_loss', 'Fat Loss'), ('endurance', 'Endurance'), ('general_fitness', 'General Fitness')], max_length=50)),
                ('is_template', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramAssignment',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('source_program_version', models.PositiveIntegerField()),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('snapshot_payload', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_program_assignments', to=settings.AUTH_USER_MODEL)),
                ('athlete_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_program_assignments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_assignments', to='organizations.organization')),
                ('source_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramPhase',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('sequence_order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_weeks', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='programs.program')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramWeek',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('week_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('focus_note', models.TextField(blank=True, null=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='programs.programphase')),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('title', models.CharField(max_length=150)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='programs.programweek')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('sequence_order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='programs.programday')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutItem',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('sequence_order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('group_key', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[A-Z][0-9]{0,2}$', 'Use a group such as A, A1, or B2.')])),
                ('segment', models.CharField(choices=[('warmup', 'Warmup'), ('main', 'Main'), ('cooldown', 'Cooldown')], default='main', max_length=20)),
                ('rest_seconds_between_sets', models.PositiveIntegerField(default=90)),
                ('coach_notes', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_items', to='exercises.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='programs.workout')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='SetPrescription',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('set_index', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('target_reps', models.CharField(max_length=50)),
                ('target_load', models.CharField(blank=True, max_length=50, null=True)),
                ('target_rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('target_rir', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('tempo', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9Xx]-[0-9Xx]-[0-9Xx]-[0-9Xx]$', 'Use tempo 3-1-1-0.')])),
                ('workout_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='programs.workoutitem')),
            ],
            options={
                'ordering': ['set_index'],
            },
        ),
        migrations.CreateModel(
            name='CoachAthleteAssignment',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('athlete_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_assignments', to=settings.AUTH_USER_MODEL)),
                ('coach_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coached_assignments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'coach_user', 'athlete_user'], name='programs_co_organiz_422f53_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'coach_user', 'athlete_user'), name='unique_coach_athlete_assignment')],
            },
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['organization', 'is_template', 'is_archived'], name='programs_pr_organiz_c28f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='programassignment',
            index=models.Index(fields=['organization', 'athlete_user', 'status'], name='programs_pr_organiz_fe6114_idx'),
        ),
        migrations.AddConstraint(
            model_name='programphase',
            constraint=models.UniqueConstraint(fields=('program', 'sequence_order'), name='unique_phase_order'),
        ),
        migrations.AddConstraint(
            model_name='programweek',
            constraint=models.UniqueConstraint(fields=('phase', 'week_number'), name='unique_phase_week'),
        ),
        migrations.AddConstraint(
            model_name='programday',
            constraint=models.UniqueConstraint(fields=('week', 'day_number'), name='unique_week_day'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(fields=('day', 'sequence_order'), name='unique_day_workout'),
        ),
        migrations.AddConstraint(
            model_name='workoutitem',
            constraint=models.UniqueConstraint(fields=('workout', 'sequence_order'), name='unique_item_order'),
        ),
        migrations.AddConstraint(
            model_name='setprescription',
            constraint=models.UniqueConstraint(fields=('workout_item', 'set_index'), name='unique_item_set_index'),
        ),
    ]
