# Generated by Django 5.2.17 on 2026-08-16 11:07

import apps.core.utils.id_generator
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_enforce_unique_active_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=16)),
                ('default_provider', models.SlugField(max_length=32)),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_account', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BillingDomainEvent',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_events', to='billing.billingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_fa', models.CharField(max_length=120)),
                ('description_en', models.CharField(blank=True, max_length=500)),
                ('description_fa', models.CharField(blank=True, max_length=500)),
                ('included_athletes', models.BooleanField(default=True, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('included_athletes', True)), name='billing_athletes_always_included')],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('provider', models.SlugField(max_length=32)),
                ('provider_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField()),
                ('unit_amount_minor', models.PositiveBigIntegerField()),
                ('interval', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], max_length=12)),
                ('trial_days', models.PositiveSmallIntegerField(default=0)),
                ('grace_period_days', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='billing.plan')),
            ],
            options={
                'ordering': ['plan__display_order', 'unit_amount_minor'],
            },
        ),
        migrations.CreateModel(
            name='CheckoutAttempt',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('provider', models.SlugField(max_length=32)),
                ('kind', models.CharField(choices=[('checkout', 'Checkout'), ('portal', 'Portal')], max_length=16)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('external_session_id', models.CharField(blank=True, max_length=255)),
                ('hosted_url', models.URLField(blank=True, max_length=500)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_attempts', to='billing.billingaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.price')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderCustomerReference',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('provider', models.SlugField(max_length=32)),
                ('external_customer_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_customers', to='billing.billingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationIssue',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('provider', models.SlugField(max_length=32)),
                ('provider_event_id', models.CharField(blank=True, max_length=255)),
                ('issue_code', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('safe_detail_key', models.CharField(max_length=120)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('billing_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_issues', to='billing.billingaccount')),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('provider', models.SlugField(max_length=32)),
                ('external_subscription_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('incomplete', 'Incomplete'), ('unpaid', 'Unpaid'), ('canceled', 'Canceled')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('grace_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('last_provider_event_created_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.billingaccount')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.price')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSummary',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('provider', models.SlugField(max_length=32)),
                ('external_invoice_id', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('uncollectible', 'Uncollectible'), ('void', 'Void')], max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField()),
                ('amount_due_minor', models.PositiveBigIntegerField(default=0)),
                ('amount_paid_minor', models.PositiveBigIntegerField(default=0)),
                ('hosted_invoice_url', models.URLField(blank=True, max_length=500, null=True)),
                ('receipt_url', models.URLField(blank=True, max_length=500, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('last_provider_event_created_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.billingaccount')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.subscription')),
            ],
            options={
                'ordering': ['-issued_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntitlementSnapshot',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('access_state', models.CharField(max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField(default=1)),
                ('billing_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_snapshot', to='billing.billingaccount')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('provider', models.SlugField(max_length=32)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('received', 'Received'), ('verified', 'Verified'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=16)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('provider_created_at', models.DateTimeField()),
                ('attempt_count', models.PositiveSmallIntegerField(default=1)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('request_id', models.CharField(blank=True, max_length=36)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('billing_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='billing.billingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='BillingAuditEvent',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=20)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(max_length=255)),
                ('previous_state', models.CharField(blank=True, max_length=32)),
                ('next_state', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=36)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_audit_events', to='billing.billingaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['billing_account', 'created_at'], name='billing_bil_billing_7f4b92_idx')],
            },
        ),
        migrations.CreateModel(
            name='BillingRoleAssignment',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('billing_admin', 'Billing administrator')], default='billing_admin', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='billing.billingaccount')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_roles_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('billing_account', 'user', 'role'), name='billing_role_assignment_uniq')],
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.CharField(default=apps.core.utils.id_generator.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(choices=[('boolean', 'Boolean'), ('integer', 'Integer limit')], max_length=16)),
                ('enabled', models.BooleanField(default=False)),
                ('integer_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('label_en', models.CharField(max_length=160)),
                ('label_fa', models.CharField(max_length=160)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='billing.plan')),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'key'), name='billing_plan_entitlement_key_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('integer_limit__isnull', True), ('kind', 'boolean')), ('kind', 'integer'), _connector='OR'), name='billing_entitlement_value_shape')],
            },
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_price_id__isnull', False)), fields=('provider', 'provider_price_id'), name='billing_provider_price_ref_uniq'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='billing_currency_upper_iso'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('currency_exponent__lte', 4)), name='billing_currency_exponent_range'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), models.Q(('provider_price_id__isnull', False), models.Q(('provider_price_id', ''), _negated=True)), _connector='OR'), name='billing_active_price_has_provider_ref'),
        ),
        migrations.AddConstraint(
            model_name='checkoutattempt',
            constraint=models.UniqueConstraint(fields=('billing_account', 'idempotency_key'), name='billing_checkout_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='providercustomerreference',
            constraint=models.UniqueConstraint(fields=('provider', 'external_customer_id'), name='billing_provider_customer_ref_uniq'),
        ),
        migrations.AddConstraint(
            model_name='providercustomerreference',
            constraint=models.UniqueConstraint(fields=('billing_account', 'provider'), name='billing_account_provider_uniq'),
        ),
        migrations.AddIndex(
            model_name='reconciliationissue',
            index=models.Index(fields=['status', 'last_seen_at'], name='billing_rec_status_2a06d8_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['billing_account', 'status'], name='billing_sub_billing_97e8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['provider', 'external_subscription_id'], name='billing_sub_provide_2c27b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('provider', 'external_subscription_id'), name='billing_provider_subscription_ref_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='billing_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['trialing', 'active', 'past_due']), _negated=True), models.Q(('current_period_start__isnull', False), ('current_period_end__isnull', False), ('current_period_end__gt', models.F('current_period_start'))), _connector='OR'), name='billing_entitled_states_have_period'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'trialing'), _negated=True), ('trial_end__isnull', False), _connector='OR'), name='billing_trial_has_end'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'canceled'), _negated=True), ('canceled_at__isnull', False), _connector='OR'), name='billing_canceled_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='invoicesummary',
            constraint=models.UniqueConstraint(fields=('provider', 'external_invoice_id'), name='billing_provider_invoice_ref_uniq'),
        ),
        migrations.AddConstraint(
            model_name='invoicesummary',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='billing_invoice_currency_iso'),
        ),
        migrations.AddConstraint(
            model_name='invoicesummary',
            constraint=models.CheckConstraint(condition=models.Q(('currency_exponent__lte', 4)), name='billing_invoice_exponent_range'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['status', 'received_at'], name='billing_web_status_459d9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='billing_webhook_event_uniq'),
        ),
    ]
