# Generated by Django 5.2.17 on 2026-08-16 11:14

import apps.copilot.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_enforce_unique_active_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderAdapterConfig',
            fields=[
                ('id', models.CharField(default=apps.copilot.models._uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('provider_kind', models.CharField(choices=[('fake', 'Deterministic fake (dev/CI)'), ('http', 'HTTP provider (declarative)')], default='fake', max_length=32)),
                ('display_name', models.CharField(max_length=120)),
                ('model_identifier', models.CharField(blank=True, default='', max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('timeout_ms', models.PositiveIntegerField(default=8000)),
                ('max_context_chars', models.PositiveIntegerField(default=12000)),
                ('max_output_tokens', models.PositiveIntegerField(default=1200)),
                ('cost_per_1k_input_micro_usd', models.PositiveIntegerField(default=0)),
                ('cost_per_1k_output_micro_usd', models.PositiveIntegerField(default=0)),
                ('retention_note', models.CharField(blank=True, default='', help_text='Declared, unverified provider retention assumption (no zero-retention claim).', max_length=240)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI provider adapter config',
                'verbose_name_plural': 'AI provider adapter configs',
            },
        ),
        migrations.CreateModel(
            name='AIRun',
            fields=[
                ('id', models.CharField(default=apps.copilot.models._uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('capability', models.CharField(choices=[('draft_check_in', 'draft_check_in'), ('suggest_program_adjustment', 'suggest_program_adjustment'), ('summarize_progress', 'summarize_progress')], max_length=64)),
                ('generation_language', models.CharField(choices=[('fa-IR', 'fa-IR'), ('en-US', 'en-US')], max_length=10)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('expired', 'expired')], max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64)),
                ('policy_version', models.CharField(max_length=40)),
                ('provider_slug', models.CharField(blank=True, default='', max_length=64)),
                ('model_identifier', models.CharField(blank=True, default='', max_length=120)),
                ('provider_request_id', models.CharField(blank=True, default='', max_length=120)),
                ('context_snapshot', models.JSONField(blank=True, null=True)),
                ('input_context_hash', models.CharField(blank=True, default='', max_length=64)),
                ('parameters_hash', models.CharField(blank=True, default='', max_length=64)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=2)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('input_tokens_est', models.PositiveIntegerField(default=0)),
                ('output_tokens_est', models.PositiveIntegerField(default=0)),
                ('cost_micro_usd', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('fallback_applied', models.BooleanField(default=False)),
                ('schema_valid', models.BooleanField(default=False)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_runs', to=settings.AUTH_USER_MODEL)),
                ('athlete_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_subject_runs', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_runs', to='organizations.organization')),
                ('regenerated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regenerations', to='copilot.airun')),
            ],
            options={
                'verbose_name': 'AI run',
                'verbose_name_plural': 'AI runs',
            },
        ),
        migrations.CreateModel(
            name='AIOutput',
            fields=[
                ('id', models.CharField(default=apps.copilot.models._uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(max_length=64)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], max_length=16)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('edited_payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('edited', 'edited'), ('approved', 'approved'), ('rejected', 'rejected'), ('quarantined', 'quarantined'), ('expired', 'expired')], default='draft', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='copilot.airun')),
            ],
            options={
                'verbose_name': 'AI output',
                'verbose_name_plural': 'AI outputs',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplateVersion',
            fields=[
                ('id', models.CharField(default=apps.copilot.models._uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('capability', models.CharField(choices=[('draft_check_in', 'draft_check_in'), ('suggest_program_adjustment', 'suggest_program_adjustment'), ('summarize_progress', 'summarize_progress')], max_length=64)),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('locale', models.CharField(choices=[('fa-IR', 'fa-IR'), ('en-US', 'en-US')], max_length=10)),
                ('template_sha256', models.CharField(max_length=64)),
                ('system_directive', models.TextField()),
                ('output_schema', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'prompt template version',
                'verbose_name_plural': 'prompt template versions',
                'constraints': [models.UniqueConstraint(fields=('capability', 'version', 'locale'), name='unique_template_version')],
            },
        ),
        migrations.AddField(
            model_name='airun',
            name='prompt_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='copilot.prompttemplateversion'),
        ),
        migrations.CreateModel(
            name='AIAuditEvent',
            fields=[
                ('id', models.CharField(default=apps.copilot.models._uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ai.run.requested', 'ai.run.requested'), ('ai.run.denied', 'ai.run.denied'), ('ai.run.completed', 'ai.run.completed'), ('ai.run.failed', 'ai.run.failed'), ('ai.run.cancelled', 'ai.run.cancelled'), ('ai.run.regenerated', 'ai.run.regenerated'), ('ai.output.viewed', 'ai.output.viewed'), ('ai.output.edited', 'ai.output.edited'), ('ai.output.approved', 'ai.output.approved'), ('ai.output.rejected', 'ai.output.rejected'), ('ai.output.reported', 'ai.output.reported'), ('ai.source.opened', 'ai.source.opened'), ('ai.purge.executed', 'ai.purge.executed')], db_index=True, max_length=40)),
                ('target_entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_entity_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=36)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'AI audit event',
                'verbose_name_plural': 'AI audit events',
                'indexes': [models.Index(fields=['action', 'created_at'], name='copilot_aia_action_ccd3d1_idx'), models.Index(fields=['organization', 'created_at'], name='copilot_aia_organiz_66bcae_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIPolicyDecision',
            fields=[
                ('id', models.CharField(default=apps.copilot.models._uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('capability', models.CharField(blank=True, default='', max_length=64)),
                ('stage', models.CharField(default='request', max_length=32)),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=8)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_decisions', to='copilot.airun')),
            ],
            options={
                'verbose_name': 'AI policy decision',
                'verbose_name_plural': 'AI policy decisions',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='copilot_aip_organiz_a7b01d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.CharField(default=apps.copilot.models._uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('unsafe', 'unsafe'), ('incorrect', 'incorrect'), ('privacy', 'privacy'), ('hallucinated_source', 'hallucinated_source'), ('other', 'other')], max_length=32)),
                ('detail', models.CharField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('triaged', 'Triaged'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reporter_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_feedback_reports', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reports', to='copilot.airun')),
            ],
            options={
                'verbose_name': 'AI feedback report',
                'verbose_name_plural': 'AI feedback reports',
                'indexes': [models.Index(fields=['run', 'report_type'], name='copilot_aif_run_id_663b80_idx')],
            },
        ),
        migrations.CreateModel(
            name='AISourceReference',
            fields=[
                ('id', models.CharField(default=apps.copilot.models._uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('workout_session', 'Workout session'), ('set_log', 'Set log'), ('feedback_flag', 'Feedback flag (non-clinical)'), ('program_assignment', 'Program assignment'), ('exercise', 'Exercise')], max_length=32)),
                ('source_id', models.CharField(max_length=64)),
                ('descriptor', models.CharField(max_length=240)),
                ('ordinal', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='copilot.airun')),
            ],
            options={
                'verbose_name': 'AI source reference',
                'verbose_name_plural': 'AI source references',
                'indexes': [models.Index(fields=['run', 'ordinal'], name='copilot_ais_run_id_c56ee9_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageMeter',
            fields=[
                ('id', models.CharField(default=apps.copilot.models._uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('input_tokens_est', models.PositiveIntegerField(default=0)),
                ('output_tokens_est', models.PositiveIntegerField(default=0)),
                ('cost_micro_usd', models.PositiveIntegerField(default=0)),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'AI usage meter',
                'verbose_name_plural': 'AI usage meters',
                'constraints': [models.UniqueConstraint(fields=('organization', 'actor_user', 'date'), name='unique_ai_meter_day')],
            },
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['organization', 'actor_user', 'created_at'], name='copilot_air_organiz_27827a_idx'),
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['organization', 'athlete_user', 'created_at'], name='copilot_air_organiz_9db4e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='airun',
            constraint=models.UniqueConstraint(fields=('organization', 'actor_user', 'idempotency_key'), name='unique_ai_run_idempotency'),
        ),
    ]
